// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/a1yama/ghq/tig-gh/internal/domain/repository/commit_repository.go
//
// Generated by this command:
//
//	mockgen -source=/Users/a1yama/ghq/tig-gh/internal/domain/repository/commit_repository.go -destination=/Users/a1yama/ghq/tig-gh/internal/mock/commit_repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/a1yama/tig-gh/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockCommitRepository is a mock of CommitRepository interface.
type MockCommitRepository struct {
	ctrl     *gomock.Controller
	recorder *MockCommitRepositoryMockRecorder
	isgomock struct{}
}

// MockCommitRepositoryMockRecorder is the mock recorder for MockCommitRepository.
type MockCommitRepositoryMockRecorder struct {
	mock *MockCommitRepository
}

// NewMockCommitRepository creates a new mock instance.
func NewMockCommitRepository(ctrl *gomock.Controller) *MockCommitRepository {
	mock := &MockCommitRepository{ctrl: ctrl}
	mock.recorder = &MockCommitRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommitRepository) EXPECT() *MockCommitRepositoryMockRecorder {
	return m.recorder
}

// Compare mocks base method.
func (m *MockCommitRepository) Compare(ctx context.Context, owner, repo, base, head string) (*models.Comparison, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compare", ctx, owner, repo, base, head)
	ret0, _ := ret[0].(*models.Comparison)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Compare indicates an expected call of Compare.
func (mr *MockCommitRepositoryMockRecorder) Compare(ctx, owner, repo, base, head any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compare", reflect.TypeOf((*MockCommitRepository)(nil).Compare), ctx, owner, repo, base, head)
}

// Get mocks base method.
func (m *MockCommitRepository) Get(ctx context.Context, owner, repo, sha string) (*models.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, owner, repo, sha)
	ret0, _ := ret[0].(*models.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockCommitRepositoryMockRecorder) Get(ctx, owner, repo, sha any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockCommitRepository)(nil).Get), ctx, owner, repo, sha)
}

// GetBranch mocks base method.
func (m *MockCommitRepository) GetBranch(ctx context.Context, owner, repo, branch string) (*models.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBranch", ctx, owner, repo, branch)
	ret0, _ := ret[0].(*models.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBranch indicates an expected call of GetBranch.
func (mr *MockCommitRepositoryMockRecorder) GetBranch(ctx, owner, repo, branch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBranch", reflect.TypeOf((*MockCommitRepository)(nil).GetBranch), ctx, owner, repo, branch)
}

// List mocks base method.
func (m *MockCommitRepository) List(ctx context.Context, owner, repo string, opts *models.CommitOptions) ([]*models.Commit, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, owner, repo, opts)
	ret0, _ := ret[0].([]*models.Commit)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCommitRepositoryMockRecorder) List(ctx, owner, repo, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCommitRepository)(nil).List), ctx, owner, repo, opts)
}

// ListBranches mocks base method.
func (m *MockCommitRepository) ListBranches(ctx context.Context, owner, repo string) ([]*models.Branch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListBranches", ctx, owner, repo)
	ret0, _ := ret[0].([]*models.Branch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListBranches indicates an expected call of ListBranches.
func (mr *MockCommitRepositoryMockRecorder) ListBranches(ctx, owner, repo any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListBranches", reflect.TypeOf((*MockCommitRepository)(nil).ListBranches), ctx, owner, repo)
}
