// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/a1yama/ghq/tig-gh/internal/domain/repository/issue_repository.go
//
// Generated by this command:
//
//	mockgen -source=/Users/a1yama/ghq/tig-gh/internal/domain/repository/issue_repository.go -destination=/Users/a1yama/ghq/tig-gh/internal/mock/issue_repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/a1yama/tig-gh/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockIssueRepository is a mock of IssueRepository interface.
type MockIssueRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIssueRepositoryMockRecorder
	isgomock struct{}
}

// MockIssueRepositoryMockRecorder is the mock recorder for MockIssueRepository.
type MockIssueRepositoryMockRecorder struct {
	mock *MockIssueRepository
}

// NewMockIssueRepository creates a new mock instance.
func NewMockIssueRepository(ctrl *gomock.Controller) *MockIssueRepository {
	mock := &MockIssueRepository{ctrl: ctrl}
	mock.recorder = &MockIssueRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIssueRepository) EXPECT() *MockIssueRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockIssueRepository) Close(ctx context.Context, owner, repo string, number int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, owner, repo, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockIssueRepositoryMockRecorder) Close(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockIssueRepository)(nil).Close), ctx, owner, repo, number)
}

// Create mocks base method.
func (m *MockIssueRepository) Create(ctx context.Context, owner, repo string, input *models.CreateIssueInput) (*models.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, owner, repo, input)
	ret0, _ := ret[0].(*models.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIssueRepositoryMockRecorder) Create(ctx, owner, repo, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIssueRepository)(nil).Create), ctx, owner, repo, input)
}

// Get mocks base method.
func (m *MockIssueRepository) Get(ctx context.Context, owner, repo string, number int) (*models.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, owner, repo, number)
	ret0, _ := ret[0].(*models.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockIssueRepositoryMockRecorder) Get(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIssueRepository)(nil).Get), ctx, owner, repo, number)
}

// List mocks base method.
func (m *MockIssueRepository) List(ctx context.Context, owner, repo string, opts *models.IssueOptions) ([]*models.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, owner, repo, opts)
	ret0, _ := ret[0].([]*models.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockIssueRepositoryMockRecorder) List(ctx, owner, repo, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockIssueRepository)(nil).List), ctx, owner, repo, opts)
}

// ListComments mocks base method.
func (m *MockIssueRepository) ListComments(ctx context.Context, owner, repo string, number int, opts *models.CommentOptions) ([]*models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComments", ctx, owner, repo, number, opts)
	ret0, _ := ret[0].([]*models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComments indicates an expected call of ListComments.
func (mr *MockIssueRepositoryMockRecorder) ListComments(ctx, owner, repo, number, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MockIssueRepository)(nil).ListComments), ctx, owner, repo, number, opts)
}

// Lock mocks base method.
func (m *MockIssueRepository) Lock(ctx context.Context, owner, repo string, number int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lock", ctx, owner, repo, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// Lock indicates an expected call of Lock.
func (mr *MockIssueRepositoryMockRecorder) Lock(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lock", reflect.TypeOf((*MockIssueRepository)(nil).Lock), ctx, owner, repo, number)
}

// Reopen mocks base method.
func (m *MockIssueRepository) Reopen(ctx context.Context, owner, repo string, number int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reopen", ctx, owner, repo, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reopen indicates an expected call of Reopen.
func (mr *MockIssueRepositoryMockRecorder) Reopen(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reopen", reflect.TypeOf((*MockIssueRepository)(nil).Reopen), ctx, owner, repo, number)
}

// Unlock mocks base method.
func (m *MockIssueRepository) Unlock(ctx context.Context, owner, repo string, number int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unlock", ctx, owner, repo, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unlock indicates an expected call of Unlock.
func (mr *MockIssueRepositoryMockRecorder) Unlock(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unlock", reflect.TypeOf((*MockIssueRepository)(nil).Unlock), ctx, owner, repo, number)
}

// Update mocks base method.
func (m *MockIssueRepository) Update(ctx context.Context, owner, repo string, number int, input *models.UpdateIssueInput) (*models.Issue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, owner, repo, number, input)
	ret0, _ := ret[0].(*models.Issue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIssueRepositoryMockRecorder) Update(ctx, owner, repo, number, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIssueRepository)(nil).Update), ctx, owner, repo, number, input)
}
