// Code generated by MockGen. DO NOT EDIT.
// Source: /Users/a1yama/ghq/tig-gh/internal/domain/repository/pr_repository.go
//
// Generated by this command:
//
//	mockgen -source=/Users/a1yama/ghq/tig-gh/internal/domain/repository/pr_repository.go -destination=/Users/a1yama/ghq/tig-gh/internal/mock/pr_repository_mock.go -package=mock
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	models "github.com/a1yama/tig-gh/internal/domain/models"
	gomock "go.uber.org/mock/gomock"
)

// MockPullRequestRepository is a mock of PullRequestRepository interface.
type MockPullRequestRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPullRequestRepositoryMockRecorder
	isgomock struct{}
}

// MockPullRequestRepositoryMockRecorder is the mock recorder for MockPullRequestRepository.
type MockPullRequestRepositoryMockRecorder struct {
	mock *MockPullRequestRepository
}

// NewMockPullRequestRepository creates a new mock instance.
func NewMockPullRequestRepository(ctrl *gomock.Controller) *MockPullRequestRepository {
	mock := &MockPullRequestRepository{ctrl: ctrl}
	mock.recorder = &MockPullRequestRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPullRequestRepository) EXPECT() *MockPullRequestRepositoryMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockPullRequestRepository) Close(ctx context.Context, owner, repo string, number int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx, owner, repo, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockPullRequestRepositoryMockRecorder) Close(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockPullRequestRepository)(nil).Close), ctx, owner, repo, number)
}

// Create mocks base method.
func (m *MockPullRequestRepository) Create(ctx context.Context, owner, repo string, input *models.CreatePRInput) (*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, owner, repo, input)
	ret0, _ := ret[0].(*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockPullRequestRepositoryMockRecorder) Create(ctx, owner, repo, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPullRequestRepository)(nil).Create), ctx, owner, repo, input)
}

// Get mocks base method.
func (m *MockPullRequestRepository) Get(ctx context.Context, owner, repo string, number int) (*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, owner, repo, number)
	ret0, _ := ret[0].(*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockPullRequestRepositoryMockRecorder) Get(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPullRequestRepository)(nil).Get), ctx, owner, repo, number)
}

// GetDiff mocks base method.
func (m *MockPullRequestRepository) GetDiff(ctx context.Context, owner, repo string, number int) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDiff", ctx, owner, repo, number)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDiff indicates an expected call of GetDiff.
func (mr *MockPullRequestRepositoryMockRecorder) GetDiff(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDiff", reflect.TypeOf((*MockPullRequestRepository)(nil).GetDiff), ctx, owner, repo, number)
}

// IsMergeable mocks base method.
func (m *MockPullRequestRepository) IsMergeable(ctx context.Context, owner, repo string, number int) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMergeable", ctx, owner, repo, number)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMergeable indicates an expected call of IsMergeable.
func (mr *MockPullRequestRepositoryMockRecorder) IsMergeable(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMergeable", reflect.TypeOf((*MockPullRequestRepository)(nil).IsMergeable), ctx, owner, repo, number)
}

// List mocks base method.
func (m *MockPullRequestRepository) List(ctx context.Context, owner, repo string, opts *models.PROptions) ([]*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, owner, repo, opts)
	ret0, _ := ret[0].([]*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockPullRequestRepositoryMockRecorder) List(ctx, owner, repo, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockPullRequestRepository)(nil).List), ctx, owner, repo, opts)
}

// ListComments mocks base method.
func (m *MockPullRequestRepository) ListComments(ctx context.Context, owner, repo string, number int, opts *models.CommentOptions) ([]*models.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListComments", ctx, owner, repo, number, opts)
	ret0, _ := ret[0].([]*models.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListComments indicates an expected call of ListComments.
func (mr *MockPullRequestRepositoryMockRecorder) ListComments(ctx, owner, repo, number, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListComments", reflect.TypeOf((*MockPullRequestRepository)(nil).ListComments), ctx, owner, repo, number, opts)
}

// ListReviews mocks base method.
func (m *MockPullRequestRepository) ListReviews(ctx context.Context, owner, repo string, number int) ([]*models.Review, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListReviews", ctx, owner, repo, number)
	ret0, _ := ret[0].([]*models.Review)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListReviews indicates an expected call of ListReviews.
func (mr *MockPullRequestRepositoryMockRecorder) ListReviews(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListReviews", reflect.TypeOf((*MockPullRequestRepository)(nil).ListReviews), ctx, owner, repo, number)
}

// Merge mocks base method.
func (m *MockPullRequestRepository) Merge(ctx context.Context, owner, repo string, number int, opts *models.MergeOptions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Merge", ctx, owner, repo, number, opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Merge indicates an expected call of Merge.
func (mr *MockPullRequestRepositoryMockRecorder) Merge(ctx, owner, repo, number, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockPullRequestRepository)(nil).Merge), ctx, owner, repo, number, opts)
}

// Reopen mocks base method.
func (m *MockPullRequestRepository) Reopen(ctx context.Context, owner, repo string, number int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reopen", ctx, owner, repo, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reopen indicates an expected call of Reopen.
func (mr *MockPullRequestRepositoryMockRecorder) Reopen(ctx, owner, repo, number any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reopen", reflect.TypeOf((*MockPullRequestRepository)(nil).Reopen), ctx, owner, repo, number)
}

// Update mocks base method.
func (m *MockPullRequestRepository) Update(ctx context.Context, owner, repo string, number int, input *models.UpdatePRInput) (*models.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, owner, repo, number, input)
	ret0, _ := ret[0].(*models.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPullRequestRepositoryMockRecorder) Update(ctx, owner, repo, number, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPullRequestRepository)(nil).Update), ctx, owner, repo, number, input)
}
